### ISSUE TITLE
Args Parser

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/Turing#14]
we should be able to retrieve a file from the program args and parse in the existing erlang `Record`.
It will allow to test several machine config in different tests
We should also be able to pass the word input after the machine config !

- [ ] pass file json in args & convert it into a `Record`
- [ ] pass the word input in args & convert it into a `list(string())`

Todo: Friday 27 may

- [x] 1/ parse_machine_alphabet & tests
- [x] 2/ parse_machine_initial & tests
- [x] https://github.com/AdonisEnProvence/Turing/issues/18
- [x] 4/ Create parser hook function that will be return error + related field for each field parser logic & tests
- [x] 5/ Refactor format_error to accept a rawMachineConfig key for each error use case & tests in already existing unit tests by statictly injecting the related rawMachineConfig field
- [x] 6/ Improve turing.erl args injection, protect the file read + use parse_machine and stop program on error + log => Integ Tests
- [x] 7/ Input/Word parser https://github.com/AdonisEnProvence/Turing/issues/16

**Comment by prastoin** [comment]
Should we check every json key ?

**Comment by Devessier** [comment]
> Should we check every json key ?

We won't ensure only known keys are in the machine config. We pick fields that interest us and forget about others.

**Comment by prastoin** [comment]
closing the issue as solved in differents PR
