### ISSUE TITLE
MachineConfig validation

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/Turing#16]
After parsing, we must validate fields between them.
Machine validation will never mutate the machine config, it will either validate it or crash the program

###  Alphabet:
- [x] duplicates are forbidden in alphabet list

### States
- [x] duplicates are forbidden in state list

### Blank
- [x] blank character **must** be in the alphabet list

### Finals
- [x] duplicates are forbidden in final state list
- [x] final states **must** be in state list

### Initial
- [x] initial state **must** be in state list

Transitions:
- [x] duplicates are forbidden in transitions list `{ "a": [{ "read": "X" }, { "read": "X" }] }`
- [x] each read character **must** be defined in alphabet
- [x] each write character **must** be defined in alphabet
- [x] each to_state **must** be defined in state list
- [x] all keys of transition dictionary **must** be defined in state list
~~- [ ] duplicates are forbidden in transitions list `{ "a": [{ "read": "X" }], "a": [{ "read": "X" }] }`~~ => The first one will be kept

**Comment by Devessier** [comment]
What do we want to do with duplicates in lists?

- Throw an error if we find duplicates
- Remove duplicates and do not throw an error (by [transforming the list into a set](https://www.erlang.org/doc/man/sets.html) for example)

**Comment by prastoin** [comment]
close as everything as been solved
